name: 'task'
description: 'Runs tasks'
inputs:
  task-path:
    description: 'Which task to run'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run
      run: |
        cd tasks
        bash task.sh ${{ inputs.task-path }}
      shell: bash

