on:
  workflow-dispatch:

jobs:
  rt:
    runs-on: ubuntu-latest
    name: RT HST
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/tasks
        with:
          task-path: hst/rt
